"""Generate the navigational documentation inventories from the docs tree."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Final


DOCS_ROOT: Final = Path(__file__).resolve().parent.parent
MARKDOWN_INDEX: Final = DOCS_ROOT / "documentation-index.md"
JSON_INDEX: Final = DOCS_ROOT / "documentation-index.json"
EXCLUDED_NAMES: Final = {MARKDOWN_INDEX.name, JSON_INDEX.name}
CATEGORY_PREFIXES: Final = (
    ("py4gw-ai/", "py4gw-ai"),
    ("architecture/", "architecture"),
    ("automation/", "automation"),
    ("bridge/", "bridge"),
    ("game-client/", "game-client"),
    ("items/", "items"),
    ("loot/", "loot"),
    ("maintenance/", "maintenance"),
    ("persistence/", "persistence"),
    ("ui/", "ui"),
    ("validation/", "validation"),
)
CATEGORY_DESCRIPTIONS: Final = {
    "py4gw-ai": "Py4GW AI operating guidance, instruction history, and agent research.",
    "architecture": "Architecture models, migration records, decisions, and project records.",
    "automation": "Bots, behavior trees, HeroAI, builds, and gameplay automation.",
    "bridge": "Bridge, shared-memory, MCP, and external operator integration.",
    "game-client": "Game-client reference, research, reverse engineering, and probes.",
    "items": "Item modifier reference, generated catalogs, and supporting tools.",
    "loot": "Loot behavior, design, and historical configuration evidence.",
    "maintenance": "Documentation policy, inventories, and maintenance records/tools.",
    "persistence": "Settings, JSON, database, and persistence-boundary records.",
    "ui": "PyImGui, overlays, frame trees, native UI research, and widgets.",
    "validation": "Demo coverage, live-client validation, and runtime evidence.",
    "needs-review": "Documents outside an owned topic that still need classification.",
}


def classify(relative_path: str) -> str:
    """Return the owned topic category for a documentation-relative path."""
    if relative_path == "README.md":
        return "maintenance"
    for prefix, category in CATEGORY_PREFIXES:
        if relative_path.startswith(prefix):
            return category
    return "needs-review"


def first_heading(path: Path) -> str:
    """Return the first Markdown heading, or an empty title for non-Markdown files."""
    if path.suffix.lower() != ".md":
        return ""

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped
    return ""


def collect_entries() -> list[dict[str, object]]:
    """Collect deterministic, source-neutral file metadata for every documentation file."""
    entries: list[dict[str, object]] = []
    for path in sorted(DOCS_ROOT.rglob("*")):
        if not path.is_file() or path.name in EXCLUDED_NAMES or "__pycache__" in path.parts:
            continue

        relative_path = path.relative_to(DOCS_ROOT).as_posix()
        entries.append(
            {
                "path": relative_path,
                "title": first_heading(path),
                "extension": path.suffix.lower(),
                "bytes": path.stat().st_size,
                "lines": len(path.read_bytes().splitlines()),
                "category": classify(relative_path),
                "review_status": "navigation-only",
            }
        )
    return entries


def markdown_table_cell(value: object) -> str:
    """Keep generated Markdown table cells to one physical line."""
    return str(value).replace("|", "\\|").replace("\n", " ")


def write_markdown(entries: list[dict[str, object]], categories: dict[str, int]) -> None:
    """Write the human-readable inventory grouped by owned topic."""
    lines = [
        "# Py4GW Documentation Index",
        "",
        "Generated by `docs/maintenance/generate_documentation_index.py`. This is a",
        "navigation inventory, not a source of behavioral authority. Start with",
        "`docs/README.md` and the nearest topic README.",
        "",
        "## Topic Counts",
        "",
        "| Category | Purpose | Files |",
        "|---|---|---:|",
    ]
    for category, count in categories.items():
        lines.append(
            f"| `{category}` | {CATEGORY_DESCRIPTIONS[category]} | {count} |"
        )

    for category in categories:
        lines.extend(
            [
                "",
                f"## {category}",
                "",
                "| Path | Title | Type | Bytes |",
                "|---|---|---|---:|",
            ]
        )
        for entry in (item for item in entries if item["category"] == category):
            title = entry["title"] or "-"
            lines.append(
                "| "
                f"`{markdown_table_cell(entry['path'])}` | "
                f"{markdown_table_cell(title)} | "
                f"`{entry['extension'] or '-'}` | {entry['bytes']} |"
            )

    MARKDOWN_INDEX.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    """Regenerate both documentation index formats."""
    entries = collect_entries()
    category_order = list(CATEGORY_DESCRIPTIONS)
    categories = {
        category: sum(entry["category"] == category for entry in entries)
        for category in category_order
    }
    payload = {
        "generated_from": "docs tree",
        "status": "navigation-only; source and runtime evidence remain authoritative",
        "excluded": [
            "documentation-index.md",
            "documentation-index.json",
            "**/__pycache__/**",
        ],
        "file_count": len(entries),
        "categories": categories,
        "entries": entries,
    }
    JSON_INDEX.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    write_markdown(entries, categories)


if __name__ == "__main__":
    main()
